In [6]:
import numpy as np

In [7]:
birthArr = np.loadtxt('data/births.txt',delimiter=',' , dtype=np.int64)
birthArr

array([[   1880,   90993,  110491],
       [   1881,   91954,  100745],
       [   1882,  107850,  113688],
       [   1883,  112321,  104629],
       [   1884,  129022,  114445],
       [   1885,  133055,  107800],
       [   1886,  144535,  110784],
       [   1887,  145982,  101414],
       [   1888,  178627,  120853],
       [   1889,  178366,  110584],
       [   1890,  190377,  111025],
       [   1891,  185482,  101196],
       [   1892,  212346,  122037],
       [   1893,  212906,  112317],
       [   1894,  222922,  115772],
       [   1895,  233630,  117398],
       [   1896,  237920,  119570],
       [   1897,  234202,  112758],
       [   1898,  258770,  122693],
       [   1899,  233023,  106212],
       [   1900,  299828,  150499],
       [   1901,  239348,  106471],
       [   1902,  264077,  122659],
       [   1903,  261973,  119234],
       [   1904,  275371,  128125],
       [   1905,  291629,  132319],
       [   1906,  295303,  133159],
       [   1907,  318566,  146833],
       [   1908,  334313,  154344],
       [   1909,  347228,  163999],
       [   1910,  396501,  194218],
       [   1911,  418299,  225968],
       [   1912,  558103,  429945],
       [   1913,  624518,  512557],
       [   1914,  761548,  654762],
       [   1915,  983874,  848603],
       [   1916, 1044323,  890099],
       [   1917, 1081280,  925511],
       [   1918, 1157647, 1013537],
       [   1919, 1130145,  980149],
       [   1920, 1198283, 1064463],
       [   1921, 1232999, 1101457],
       [   1922, 1200919, 1088287],
       [   1923, 1206330, 1096168],
       [   1924, 1248876, 1132751],
       [   1925, 1217352, 1115958],
       [   1926, 1185304, 1110505],
       [   1927, 1192330, 1126717],
       [   1928, 1153117, 1107518],
       [   1929, 1116422, 1075313],
       [   1930, 1125761, 1097176],
       [   1931, 1064497, 1039127],
       [   1932, 1066994, 1043808],
       [   1933, 1007710,  991127],
       [   1934, 1044039, 1032291],
       [   1935, 1048428, 1040930],
       [   1936, 1040202, 1036974],
       [   1937, 1063872, 1066309],
       [   1938, 1103277, 1108841],
       [   1939, 1096518, 1106544],
       [   1940, 1143325, 1158900],
       [   1941, 1207919, 1227941],
       [   1942, 1350545, 1380774],
       [   1943, 1395082, 1426846],
       [   1944, 1327104, 1362555],
       [   1945, 1307028, 1345610],
       [   1946, 1571184, 1623650],
       [   1947, 1772644, 1829223],
       [   1948, 1697814, 1754469],
       [   1949, 1710825, 1773725],
       [   1950, 1713180, 1790673],
       [   1951, 1800042, 1881080],
       [   1952, 1854698, 1944277],
       [   1953, 1880326, 1969777],
       [   1954, 1941682, 2037374],
       [   1955, 1954664, 2057918],
       [   1956, 2007512, 2113694],
       [   1957, 2044160, 2155866],
       [   1958, 2010884, 2120712],
       [   1959, 2023044, 2133509],
       [   1960, 2022093, 2132717],
       [   1961, 2017316, 2122502],
       [   1962, 1966548, 2068945],
       [   1963, 1927217, 2031755],
       [   1964, 1894594, 1993270],
       [   1965, 1765001, 1861378],
       [   1966, 1691868, 1783964],
       [   1967, 1650764, 1744527],
       [   1968, 1640103, 1738928],
       [   1969, 1686947, 1789732],
       [   1970, 1748147, 1859594],
       [   1971, 1663475, 1769201],
       [   1972, 1521185, 1622666],
       [   1973, 1458139, 1559338],
       [   1974, 1467413, 1573105],
       [   1975, 1457699, 1562207],
       [   1976, 1465096, 1569904],
       [   1977, 1532997, 1643684],
       [   1978, 1531658, 1642250],
       [   1979, 1605051, 1721947],
       [   1980, 1659933, 1783876],
       [   1981, 1667465, 1790907],
       [   1982, 1692678, 1813970],
       [   1983, 1670061, 1791732],
       [   1984, 1682973, 1803830],
       [   1985, 1720036, 1847032],
       [   1986, 1714664, 1840164],
       [   1987, 1737891, 1865662],
       [   1988, 1779839, 1912602],
       [   1989, 1843105, 1999999],
       [   1990, 1897709, 2052543],
       [   1991, 1874434, 2019463],
       [   1992, 1843304, 1996388],
       [   1993, 1808379, 1960397],
       [   1994, 1785074, 1931157],
       [   1995, 1757927, 1902832],
       [   1996, 1752249, 1893378],
       [   1997, 1739806, 1884122],
       [   1998, 1765915, 1910250],
       [   1999, 1772632, 1918809],
       [   2000, 1814601, 1962406],
       [   2001, 1799049, 1941251],
       [   2002, 1795206, 1939815],
       [   2003, 1825359, 1973434],
       [   2004, 1834145, 1982794],
       [   2005, 1845379, 1994841],
       [   2006, 1898463, 2052377],
       [   2007, 1919408, 2072139],
       [   2008, 1887234, 2036289],
       [   2009, 1832925, 1979303],
       [   2010, 1772738, 1913851],
       [   2011, 1753500, 1893230]], dtype=int64)

In [ ]:
#미국에서 태어난 년도, 남아수, 여아수 (1880~2011)

In [5]:
birthArr.shape

(132, 3)

In [16]:
birthArr.mean(axis=0).round(2)

array([   1945.5 , 1225776.07, 1245399.21])

In [17]:
# 1. 남아 ,여아 출생 평균을 구하시요
# y,m,f = birthArr.mean(axis=0)
# print('남아평균',round(m,2) )
# print('여아평균',round(f,2) )
y,m,f = birthArr.mean(axis=0).round(2)
print('남아평균',m )
print('여아평균',f )

남아평균 1225776.07
여아평균 1245399.21

In [25]:
# 2. 2000년대 이후데이터를 구하시요
# 년도   남아   여아
# ==============
# 2000     xx     xx
print('년도','남아','여아',sep='\t')
print('='*30)
for y,m,f in birthArr[ birthArr[:,0] >=2000 ]:
    print(y,m,f)

년도	남아	여아
==============================
2000 1814601 1962406
2001 1799049 1941251
2002 1795206 1939815
2003 1825359 1973434
2004 1834145 1982794
2005 1845379 1994841
2006 1898463 2052377
2007 1919408 2072139
2008 1887234 2036289
2009 1832925 1979303
2010 1772738 1913851
2011 1753500 1893230

In [33]:
# 3. 남아출생이 가장많은 년도와 남아수를 구하시요.
mx = birthArr[:,1].max()
for y,m,f in birthArr[ birthArr[:,1] == mx ]:
    print('년도:',y, '남아수:',m)
# birthArr[birthArr[:,1] == 2044160]

년도: 1957 남아수: 2044160

In [ ]:
# 4. 남아출생이 가장많은 top5 를 구하시요(년도와 남아수)
a= np.argsort(birthArr[:,1], axis=0)[:-6:-1]
birthArr[a,:2]

In [39]:
idx = np.argsort( birthArr[:,1] )[:-6:-1]
birthArr[ idx ][:, [0,1] ]

array([[   1957, 2044160],
       [   1959, 2023044],
       [   1960, 2022093],
       [   1961, 2017316],
       [   1958, 2010884]], dtype=int64)

In [ ]:
5. 남아율(%) 을 구하고 각년도별
남아수가 차지하는비율을 데이터로
보여주시요.
남아    여아    남아율
===================
..

In [47]:
m = birthArr[:,1]
w = birthArr[:,2]
ratio = (m/(m+w))*100
print('='*20)
print('남아','여아','남아율',sep='\t')
print('='*20)
for m,w,r in zip(m,w,ratio.round(2)):
    print(m, w, r,sep='\t')

====================
남아	여아	남아율
====================
90993	110491	45.16
91954	100745	47.72
107850	113688	48.68
112321	104629	51.77
129022	114445	52.99
133055	107800	55.24
144535	110784	56.61
145982	101414	59.01
178627	120853	59.65
178366	110584	61.73
190377	111025	63.16
185482	101196	64.7
212346	122037	63.5
212906	112317	65.46
222922	115772	65.82
233630	117398	66.56
237920	119570	66.55
234202	112758	67.5
258770	122693	67.84
233023	106212	68.69
299828	150499	66.58
239348	106471	69.21
264077	122659	68.28
261973	119234	68.72
275371	128125	68.25
291629	132319	68.79
295303	133159	68.92
318566	146833	68.45
334313	154344	68.41
347228	163999	67.92
396501	194218	67.12
418299	225968	64.93
558103	429945	56.49
624518	512557	54.92
761548	654762	53.77
983874	848603	53.69
1044323	890099	53.99
1081280	925511	53.88
1157647	1013537	53.32
1130145	980149	53.55
1198283	1064463	52.96
1232999	1101457	52.82
1200919	1088287	52.46
1206330	1096168	52.39
1248876	1132751	52.44
1217352	1115958	52.17
1185304	1110505	51.63
1192330	1126717	51.41
1153117	1107518	51.01
1116422	1075313	50.94
1125761	1097176	50.64
1064497	1039127	50.6
1066994	1043808	50.55
1007710	991127	50.41
1044039	1032291	50.28
1048428	1040930	50.18
1040202	1036974	50.08
1063872	1066309	49.94
1103277	1108841	49.87
1096518	1106544	49.77
1143325	1158900	49.66
1207919	1227941	49.59
1350545	1380774	49.45
1395082	1426846	49.44
1327104	1362555	49.34
1307028	1345610	49.27
1571184	1623650	49.18
1772644	1829223	49.21
1697814	1754469	49.18
1710825	1773725	49.1
1713180	1790673	48.89
1800042	1881080	48.9
1854698	1944277	48.82
1880326	1969777	48.84
1941682	2037374	48.8
1954664	2057918	48.71
2007512	2113694	48.71
2044160	2155866	48.67
2010884	2120712	48.67
2023044	2133509	48.67
2022093	2132717	48.67
2017316	2122502	48.73
1966548	2068945	48.73
1927217	2031755	48.68
1894594	1993270	48.73
1765001	1861378	48.67
1691868	1783964	48.68
1650764	1744527	48.62
1640103	1738928	48.54
1686947	1789732	48.52
1748147	1859594	48.46
1663475	1769201	48.46
1521185	1622666	48.39
1458139	1559338	48.32
1467413	1573105	48.26
1457699	1562207	48.27
1465096	1569904	48.27
1532997	1643684	48.26
1531658	1642250	48.26
1605051	1721947	48.24
1659933	1783876	48.2
1667465	1790907	48.22
1692678	1813970	48.27
1670061	1791732	48.24
1682973	1803830	48.27
1720036	1847032	48.22
1714664	1840164	48.23
1737891	1865662	48.23
1779839	1912602	48.2
1843105	1999999	47.96
1897709	2052543	48.04
1874434	2019463	48.14
1843304	1996388	48.01
1808379	1960397	47.98
1785074	1931157	48.03
1757927	1902832	48.02
1752249	1893378	48.06
1739806	1884122	48.01
1765915	1910250	48.04
1772632	1918809	48.02
1814601	1962406	48.04
1799049	1941251	48.1
1795206	1939815	48.06
1825359	1973434	48.05
1834145	1982794	48.05
1845379	1994841	48.05
1898463	2052377	48.05
1919408	2072139	48.09
1887234	2036289	48.1
1832925	1979303	48.08
1772738	1913851	48.09
1753500	1893230	48.08

In [ ]:
6. 2000년도 이후데이터 에 대해
출생량 을 구하고
남아수가 1800000 이상이면 '많음'아니면 '적음'
이라고 보여 주시요
	남아수 출생량
2000   1233   '많음'
2001   1234   '적음'

In [51]:
birth20 = birthArr[birthArr[:,0] >= 2000]
result = np.where( birth20[:,1] > 1800000, '많음', '적음')

print('='*20)
print('연도','남아수','출생량',sep='\t')
print('='*20)
for a, b, c in zip(birth20[:,0], birth20[:,1], result):
    print(a, b, c, sep='\t')

====================
연도	남아수	출생량
====================
2000	1814601	많음
2001	1799049	적음
2002	1795206	적음
2003	1825359	많음
2004	1834145	많음
2005	1845379	많음
2006	1898463	많음
2007	1919408	많음
2008	1887234	많음
2009	1832925	많음
2010	1772738	적음
2011	1753500	적음

In [ ]:
# 7. 1800년대,1900년대,2000년대 
# 각 남아,여야수 평균을 구하시요

In [61]:
b1800=birthArr[birthArr[:,0]<1900]
b1900=birthArr[ (birthArr[:,0]>=1900) & (birthArr[:,0]<2000)]
b2000=birthArr [birthArr[:,0]>=2000]
y, m ,f = b1800.mean(axis=0)
print( '1800년대','남아평균:',m, '여야평균:',f)
y, m ,f = b1900.mean(axis=0)
print( '1900년대','남아평균:',m, '여야평균:',f)
y, m ,f = b2000.mean(axis=0).round(2)
print( '2000년대','남아평균:',m, '여야평균:',f)

1800년대 남아평균: 176714.15 여야평균: 111820.55
1900년대 남아평균: 1362901.51 여야평균: 1384145.55
2000년대 남아평균: 1831500.58 여야평균: 1978477.5

In [ ]:
# 8. 여아 25%~75%사이의 값을 구하시요
G = birthArr[:,-1]
q25,q75 =np.percentile( G,q=[25,75],axis=0)
G[(G >= q25) & (G <= q75)]